### ISSUE TITLE
[Feature Request] remove paragraph break

### ISSUE THREAD

**Issue by 3xploiton3** [HandcartCactus/obsidian-remove-newlines#2]
i copy text from facebook comment
![image](https://github.com/user-attachments/assets/d62ef09a-fb6b-4cc3-b7e0-8fbf7b003e6d)

Paste to obsidian
![image](https://github.com/user-attachments/assets/8ae8e358-48b3-43f0-b58c-c0cbad128bae)

our expect
![image](https://github.com/user-attachments/assets/604c4de6-9753-4943-8d4f-961fcae5a117)

**Comment by HandcartCactus** [comment]
Thank you for the feature request! I have added this feature in v`1.0.5`. Please update the plugin and let me know what you think.
