### ISSUE TITLE
Invoking commands from the command panel is broken, but right-click command works fine

### ISSUE THREAD

**Issue by dtinhvo** [HandcartCactus/obsidian-remove-newlines#4]
When I remove newlines or paste without newlines from command bar, the cursor is thrown up in the document while nothing is pasted or formatted. If I do these actions while my cursor is on a list environment, the frontmatter is messed up - newlines are added in front of the document. However, right click commands are perfectly fine.

**Comment by HandcartCactus** [comment]
I'm sorry to hear it doesn't work as intended. Thank you for creating an issue! Could you give me some more information on your environment? 

1. What OS are you using?
2. Is your obsidian version the most recent one, or are you using a much older version?
3. Do you have any other text-editimg related plugins installed?
4. Can you give me a minimal example that duplicates the bug? 

That would allow me to duplicate and study the bug so I may fix it.

**Comment by HandcartCactus** [comment]
I'm sorry to hear it doesn't work as intended. Thank you for creating an issue! I was able to replicate this bug (source mode on, linux/AppImage), so I will start working on it soon.

**Comment by HandcartCactus** [comment]
Should be fixed now in `1.0.4`. Thank you for reporting the bug. Please update your plugin and let me know if it works.

**Comment by dtinhvo** [comment]
This works now, many thanks!
