### ISSUE TITLE
Broken words ("exam- ple") are not fixed when using "Paste without newlines"

### ISSUE THREAD

**Issue by machado-t** [HandcartCactus/obsidian-remove-newlines#5]
While using command "Remove newlines from selection" fixes words that were broken across different lines, the command "Paste without newlines" leaves them like this: "exam- ple".

Can this be fixed? Thanks

**Comment by HandcartCactus** [comment]
I am sorry to hear it is not working as expected. If you could provide me with some text that causes the bug to happen, it would be extremely helpful.

The text `exam- \nple` or `exam-\n ple` (space before or after the newline) would not be matched by my current regular expression, meaning it would not be corrected by either command. I want to make sure that's not the cause.

The same regular expression is used by both the right-click and command pallette commands, so I am investigating why there would be a difference. Users have been reporting recent issues with the command pallette and the editor...

**Comment by HandcartCactus** [comment]
I am having trouble duplicating this bug.

**Comment by machado-t** [comment]
> If you could provide me with some text that causes the bug to happen, it would be extremely helpful.

```
In prior papers in this series devoted to the Grading of 
Recommendations Assessment, Development, and Evalua-
tion (GRADE) approach to systematic reviews and practice
```

If I paste it normally, and then do "Remove newlines from selection", i get:

`In prior papers in this series devoted to the Grading of Recommendations Assessment, Development, and Evaluation (GRADE) approach to systematic reviews and practice`

But if I paste it using "Paste without newlines" i get:

`In prior papers in this series devoted to the Grading of Recommendations Assessment, Development, and Evalua- tion (GRADE) approach to systematic reviews and practice`

**Comment by machado-t** [comment]
> Users have been reporting recent issues with the command pallette and the editor...

I'm also having the same issue in #4 where if I use the command palette to "Remove newlines from selection" it doesn't work and messes with the frontmatter, but clicking the command in the right-click editor menu works without a problem.

**Comment by machado-t** [comment]
> > If you could provide me with some text that causes the bug to happen, it would be extremely helpful.
> 
> ```
> In prior papers in this series devoted to the Grading of 
> Recommendations Assessment, Development, and Evalua-
> tion (GRADE) approach to systematic reviews and practice
> ```

Actually, I cannot replicate my own issue if I copy that same text from github! 
I guess this only happens when copying text directly from the original PDF. Here it is:

[Andrews_2013_GRADE_guidelines_-_14._Going_from_evidence_to_recommendations_-_the_significance.pdf](https://github.com/user-attachments/files/17619820/Andrews_2013_GRADE_guidelines_-_14._Going_from_evidence_to_recommendations_-_the_significance.pdf)

That segment of text is the first three lines from the Introduction of the paper.

**Comment by HandcartCactus** [comment]
Thank you. I believe the details you provided will be extremely helpful. I'll look into it tonight.

**Comment by HandcartCactus** [comment]
It was CR LF line endings in the PDF. I added support for CR, LF, and CR LF line endings. Thank you for reporting the bug. Please update your plugin to `1.0.4` and let me know if it works. If not, I can re-open the issue.

**Comment by machado-t** [comment]
It works! Thanks!
