### ISSUE TITLE
[BUG] "Paste without newlines" hotkey performs regular paste

### ISSUE THREAD

**Issue by machado-t** [HandcartCactus/obsidian-remove-newlines#6]
**Describe the bug**
When using a hotkey to the "Paste without newlines" command, the command performs a regular paste, keeping all newlines instead of removing them.

**To Reproduce**

1. Assign a hotkey to the "Paste without newlines" command.
2. Use the assigned hotkey to paste copied text with newlines.
3. Observe that the paste action keeps newlines as in a regular paste.

**Text which caused the bug to occur**
```markdown
This is a sample text
that demonstrates the issue.
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Obsidian Version 1.7.5

**Comment by HandcartCactus** [comment]
Was it CTRL+V? Some keybindings cannot be overridden in Obsidian.

**Comment by machado-t** [comment]
For some reason it is working now. 
It was CTRL+ALT+V but I also tried with different keybindings to be sure.

**Comment by HandcartCactus** [comment]
Hm. Let me look into if there's any plugin reload or unload actions I need to make to keep it more stable.
